insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('computer', 'Electronic', 1000, 'samsung', 1, 'Latest computer')
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('bicycle', 'vehicle', 100, 'samchunlee', 2, 'full carbon')
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('tank', 'weapon', 1000000, 'porsche', 1, 'VK 45.01(P)')
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('smartphone', 'Electronic', 1000, 'apple', 1, 'iPhone 11')
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('car', 'vehicle', 100000, 'ferrari', 1, '812superfast')
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('rifle', 'weapon', 10000, 'ADD', 3, 'K-2')
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('TV', 'Electronic', 1000, 'LG', 1, 'Latest TV')
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('boat', 'vihicle', 100000, 'hyundai', 1, 'MARK 3')
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('cannon', 'weapon', 1000000, 'america', 1, 'm7 prist')
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ('man', 'man', 1, 'home', 1, 'its me')
